#!/bin/bash

zenity --info --title="Fresh Install Tool" --text="Let's walk though what software you want on this installation." --width=250 --height=100

# Trying to use this to add system info from the os-release file WIP
versionStr=$(cat /etc/os-release | awk -F "\"" '/PRETTY_NAME/ {print $2}')

# Intro
zenity --info --title="Fresh Install Tool" --text="Welcome to your new $versionStr system." --width=300 --height=100

# Running 'apt update'
zenity --info --title="Fresh Install Tool" --text="Let's make sure your sources are up to date." --width=300 --height=100
zenity --password | sudo -Sk apt update

# Snapd installation check
# -----------------
   if [ $(dpkg-query -W -f='${Status}' snapd 2>/dev/null | grep -c "ok installed") -eq 0 ];
      then
	echo ""
	echo "First we have to install the necessary tools:"
	echo ""
	echo "  → snapd"
	echo ""
	  sudo apt-get install -qq -y snapd;
   fi

# Browser choice
# -----------------
browserchoice=$(zenity --list --width=500 --height=250 --window-icon=question --checklist \
	--title="browserchoices" --column="Pick" --column="Choices" \
	FALSE Vivaldi FALSE Chrome FALSE Chromium FALSE None --separator=":")

if [ "$browserchoice" = "Vivaldi" ]; then
zenity --info --text="You have choosen Vivaldi" --width=250 --height=100
 VERSION=$(curl https://vivaldi.com/download/ -s | awk '/amd64.deb/ {print $3}' | cut -f2 -d"\"")
 wget $VERSION
zenity --password | sudo -Sk dpkg -i $VERSION

elif [ "$browserchoice" = "Chrome" ]; then
   wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
   sudo dpkg -i google-chrome-stable_current_amd64.deb
   sudo apt -f install

elif [ "$browserchoice" = "Chromium" ]; then
   PASSWORD=$(zenity --password)
   echo $PASSWORD | sudo -S apt install chromium-browser

elif [ "$browserchoice" = "None" ]; then
   echo "No selection picked"
   graphicchoice

fi

# Graphics choice
# -----------------
graphicchoice=$(zenity --list --width=500 --height=250 --checklist \
    --title="graphicchoice" --column="Pick" --column="Choices" \
    FALSE GIMP FALSE Inkscape None --separator=":")

if [ "$graphicchoice" = "GIMP" ]; then
  zenity --info --text="You have choosen GIMP" --width=250 --height=100
  zenity --password | sudo -Sk sudo apt install gimp

fi
